/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Leon
 */
public class NewPetPanelF extends javax.swing.JPanel {

    String petname;
    int pettype;
    NewPet np;
    MainMenu mm;
    Animal pet;

    /**
     * Creates new form NewPetPanelF
     * @param mm
     */
    public NewPetPanelF(MainMenu mm) {
        this.np = new NewPet();
        this.mm = mm;
        this.pet = null;
        this.petname = "Enter pet name here";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        title = new javax.swing.JLabel();
        dogbutton = new javax.swing.JButton();
        catbutton = new javax.swing.JButton();
        createbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        petnamefield = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        title.setText("Make your pet");

        dogbutton.setText("Dog");
        dogbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogbuttonActionPerformed(evt);
            }
        });

        catbutton.setText("Cat");
        catbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catbuttonActionPerformed(evt);
            }
        });

        createbutton.setText("Create");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        cancelbutton.setText("Cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(petnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dogbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(catbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(petnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catbutton)
                    .addComponent(dogbutton))
                .addGap(42, 42, 42)
                .addComponent(createbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(cancelbutton)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    // selects dog as type
    private void dogbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogbuttonActionPerformed
        this.pettype = 1;
        this.title.setText("Dog selected");
    }//GEN-LAST:event_dogbuttonActionPerformed

    // selects cat as type
    private void catbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catbuttonActionPerformed
        this.pettype = 2;
        this.title.setText("Cat selected");
    }//GEN-LAST:event_catbuttonActionPerformed

    // creates a pet from user input
    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
        this.petname = this.petnamefield.getText();
        this.pet = np.newPet(pettype, petname);

        if (this.pet != null) {
            mm.setpet(this.pet);
            mm.changeto_playmenu();

            this.petname = "Enter pet name here";
            this.title.setText(this.petname);
            this.pettype = 0;
        } else {
            this.title.setText("Please select the type or enter a name");
        }
    }//GEN-LAST:event_createbuttonActionPerformed

    // go back to main menu
    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        mm.changeto_mainmenu();

    }//GEN-LAST:event_cancelbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbutton;
    private javax.swing.JButton catbutton;
    private javax.swing.JButton createbutton;
    private javax.swing.JButton dogbutton;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField petnamefield;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
