
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Leon
 */
public class PlayPanelF extends javax.swing.JPanel {

    MainMenu mm;
    boolean confirm;

    /**
     * Creates new form PLayPanelF
     *
     * @param mm
     */
    public PlayPanelF(MainMenu mm) {

        this.mm = mm;
        initComponents();
    }

    public void initialise() throws Exception{
        this.info.setText(mm.getpet().getName() + " wants to play! Mood:" + mm.getpet().getStatus());
        BufferedImage img;
        if (mm.getpet().getClass().toString().equals("class Dog")) {
            img = ImageIO.read(new File("dog.jpg")); 
        } else {
            img = ImageIO.read(new File("cat.jpg")); 
        }
        ImageIcon icon = new ImageIcon(img);
        imglabel.setIcon(icon);
        this.confirm = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info = new javax.swing.JLabel();
        playwithbutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        loadbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        quitbutton = new javax.swing.JButton();
        imglabel = new javax.swing.JLabel();

        info.setText("info");

        playwithbutton.setText("Play with pet");
        playwithbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playwithbuttonActionPerformed(evt);
            }
        });

        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        loadbutton.setText("Load");
        loadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        quitbutton.setText("Back");
        quitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imglabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loadbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(203, 203, 203))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(playwithbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(playwithbutton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadbutton)
                    .addComponent(savebutton))
                .addGap(18, 18, 18)
                .addComponent(deletebutton)
                .addGap(45, 45, 45)
                .addComponent(quitbutton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playwithbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playwithbuttonActionPerformed
        PlaywithPet pwp = new PlaywithPet();
        pwp.playwith(mm.getpet());
        info.setText(mm.getpet().Mood());
    }//GEN-LAST:event_playwithbuttonActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed

        info.setText("Saving");
        SavePet sp = new SavePet();
        sp.save(mm.getpet(), mm.getuname());
        info.setText("Saved!");
    }//GEN-LAST:event_savebuttonActionPerformed

    private void loadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbuttonActionPerformed
        
        mm.loadpetpanel.initialise(); // to make the list of user's pets after they log in
        mm.changeto_loadpetmenu();
    }//GEN-LAST:event_loadbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if (confirm == false) {
            confirm = true;
            info.setText("Press again to confirm deletion of " + mm.getpet().getName());
        } else {
            DeletePet dp = new DeletePet(mm);
            dp.delete(mm.getuname(), mm.getpet().getName());

            //uninitialise();
            mm.changeto_mainmenu();
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void quitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitbuttonActionPerformed
        //uninitialise();
        mm.setpet(null);
        mm.changeto_mainmenu();
    }//GEN-LAST:event_quitbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebutton;
    private javax.swing.JLabel imglabel;
    private javax.swing.JLabel info;
    private javax.swing.JButton loadbutton;
    private javax.swing.JButton playwithbutton;
    private javax.swing.JButton quitbutton;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
}
